AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Chatbot

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs22.x
    MemorySize: 128

Resources:
  ChatbotFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: chatbot.handler
      CodeUri: ./lambda/
      Environment:
        Variables:
          REGION: us-west-2
      Events:
        ChatbotApi:
          Type: Api
          Properties:
            Path: /chatbot
            Method: POST
