name: Deploy Lambda SAM

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Install AWS SAM CLI
        run: |
          pip install --upgrade pip
          pip install aws-sam-cli

      # Optional: Run tests if you have any
      #- name: Run tests
      #  run: pytest

      - name: Deploy SAM application
        run: |
          sam build
          sam deploy --no-confirm-changeset --stack-name my-portfolio-stack --capabilities CAPABILITY_IAM